### ISSUE TITLE
[Hugo Migration] Determine setup for `groups`

### ISSUE THREAD

**Issue by ionlights** [ucfai/ucfai.org#11]
Every group should have a programmatic setup, which is run during `semester-setup`

## Tasks:
- [x] (`🔑Required`) Display group meeting date, time, and room.
- [x] (`🔑Required`) Display group's Coordinators (this should be based on info in their author page).
- [x] (`🔑Required`) Display an abbreviated syllabus (should be title, banner image, and a summary).

**Use the above information to design the necessary front-matter that we can extract and to determine the needed changes to HTML layout files.**
- [ ] (`🔑Required`) Extract Jinja2 template for the group setup. This should be in `autobot/templates/seed/website/group.md.j2` but render to `groups/<group>/<semester>/_index.md`.
   - This should be done both during `semester-setup` and `semester-upkeep`, as we may bring on Coordinators during the semester.
- [ ] (`🔑Required`) Fill out as much info as possible from the `syllabus.yml` and `overhead.yml` files. (This should also be Jinja2 ready.)

**Note on Tasks:** While these are ultimately going to be the `autobot`, we need to first design these templates and see how they look on the website itself before extracting the template content into `autobot`.

**Comment by jmuchovej** [comment]
Didn't need the latter two items – Hugo was able to extract most of that from the literal posts themselves. Also didn't need a Jinja template, just needed to insert some shortcodes into the `<group>/<semester>/_index.md` for things to play nicely.

(Based on how `goldmark` parses ToCs.)
