### ISSUE TITLE
[Hugo Migration] Migrate Notebook posts to Academic's "Documentation" setup

### ISSUE THREAD

**Issue by ionlights** [ucfai/ucfai.org#8]
Mostly posting here for posterity, @causallycausal and @ionlights have already finished most of this.

## Tasks:
- [x] (`🔑Required`) Test present markdown renderings on ucfai.org in `hugo-academic`'s Documentation structure
- [x] (`🔑Required`) **Added on 01/07** Markdown is needed for ToC to work, however `pygments` doesn't work unless code is rendered in HTML. _This mandated changes to `autobot` to combine the rendering of Markdown and HTML (in specific sections). 
- [x] (`🔑Required`) Extract front-matter that needs to be filled out for `autobot`, place this in `autobot/templates/notebooks/hugo-front-matter.html.j2`. The corresponding places to make edits for this in `autobot` are here: https://github.com/ucfai/bot/blob/836879d680805c5a86de505666011c175fba39a5/autobot/utils/ucfai_exporter.py#L70
There's some string concatenation that needs to be done, but otherwise, we should be able to use the `FilesWriter` that's already present.

**Comment by ionlights** [comment]
We still need to test the generalizing of our work on this. This partially involves editing `autobot`, but an incoming commit will have some demo files to work from.
